export const MODULES = {
  PROPERTY: "PROPERTY",
  INQUIRY: "INQUIRY",
  APPRAISAL: "APPRAISAL",
  TITLING: "TITLING",
  CONSULTANCY: "CONSULTANCY",
  PROPERTY_REQUEST: "PROPERTY_REQUEST",
};

export const OWNER_TYPES = {
  PROPERTY: "Property",
  BUYER_INQUIRY: "BuyerInquiry",
  PROPERTY_REQUEST: "PropertyListingRequest",
  APPRAISAL_REQUEST: "AppraisalRequest",
  TITLING_REQUEST: "TitlingRequest",
  CONSULTANCY_REQUEST: "ConsultancyRequest",
  USER: "User",
};

export const CATEGORIES = {
  PROPERTY: ["PHOTO", "ATTACHMENT"],
  INQUIRY: ["ATTACHMENT", "PHOTO"],
  APPRAISAL: ["ATTACHMENT", "PHOTO"],
  TITLING: ["ATTACHMENT", "PHOTO"],
  CONSULTANCY: ["ATTACHMENT", "PHOTO"],
  PROPERTY_REQUEST: ["ATTACHMENT", "PHOTO"],
};

export const REGISTRY = {
  [MODULES.PROPERTY]: {
    ownerTypes: [OWNER_TYPES.PROPERTY],
    categories: CATEGORIES.PROPERTY,
  },
  [MODULES.INQUIRY]: {
    ownerTypes: [OWNER_TYPES.BUYER_INQUIRY],
    categories: CATEGORIES.INQUIRY,
  },
  [MODULES.APPRAISAL]: {
    ownerTypes: [OWNER_TYPES.APPRAISAL_REQUEST],
    categories: CATEGORIES.APPRAISAL,
  },
  [MODULES.TITLING]: {
    ownerTypes: [OWNER_TYPES.TITLING_REQUEST],
    categories: CATEGORIES.TITLING,
  },
  [MODULES.CONSULTANCY]: {
    ownerTypes: [OWNER_TYPES.CONSULTANCY_REQUEST],
    categories: CATEGORIES.CONSULTANCY,
  },

  [MODULES.PROPERTY_REQUEST]: {
    ownerTypes: [OWNER_TYPES.PROPERTY_REQUEST],
    categories: CATEGORIES.PROPERTY_REQUEST,
  },
};

export const MODULE_LIST = Object.values(MODULES);
